packages:
  - .updater
  - .web

allowBuilds:
  "@parcel/watcher": true
  esbuild: false
  workerd: false
blockExoticSubdeps: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@sakamichi-blog-archive/utils@0.8.0"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "chokidar@4.0.3"
  - "semver@6.3.1"
